

from langchain.agents import create_agent



model = "qwen3"

def run_llm_service():
    '''Run the LLM service.
    
    Args:
        query (str): The user's question

    Returns:
        Dictionary containing:
            - answer (str): The answer generated by the LLM.
            - sources (List[str]): List of sources used to generate the answer.
    
    
    '''

    system_prompt = "You are a helpful assistant that provides accurate and concise answers based on the provided context. " \
    "If the answer is not in the context, " \
    "respond with 'I don't know.'" \
    "you can answer in any language, but you must answer in the same language as the question. " \
    "If the question is not clear, ask for clarification. " \
    "If the question is not related to the context, respond with 'I don't know.'"
    "Do not assume any information that is not provided in the context. " \
    "If the context is empty, respond with 'I don't know.'"


    agent = create_agent(
        model=model,
        tool_names=["vectorstore"],
        system_prompt=system_prompt
        )
    
    messages = [
        {"role": "user", "content": query},]
    
    response  = agent.invoke({"messages": messages})
    answer = response["messages"][-1]["content"]

    context_docs=[]
    for message in response["messages"]:
        if message["role"] == "tool":
            context_docs.extend(message["content"])

    return {"answer": answer, "context": context_docs}
